### ISSUE TITLE
Wrong game server folder chown after server installation by steamcmd

### ISSUE THREAD

**Issue by iTeeLion** [gameap/daemon#8]
After game server installing by steamcmd server folder has root:root chown, with default chmod 755 it does not allow to run server from another user.
Need to chown game server directory by value from "Su user" filed in panel game server settings or the same but before every server start.

**Comment by et-nik** [comment]
Hi @iTeeLion. Thanks for this issue.

Chown command exists in installator component. I guess this code not executed:
https://github.com/gameap/GDaemon2/blob/master/src/classes/game_server_installer.cpp#L66

**Comment by et-nik** [comment]
Fixed in new version
